Repository ubuntu-common/creo, pull requests merged in 2022-06, with the labels that each got.

#5 #2 : add depi dependency installer
  depi/README.md
  depi/assets/art.dat
  depi/assets/massage.dat
  depi/assets/packages/arch.dat
  depi/assets/packages/ubuntu.dat
  depi/depi.py
Labels: Strategic, Python, External Contribution

#6 #3 : Makefile script for preparing rootfs and caching packages
  .gitignore
  creo/Makefile
  creo/hooks/chroot/00-prepare.chroot
Labels: Strategic, Make

#12 #11 : Refactoring and scaling preparing for 'creo/scripts/getdeps.py' script
  creo/scripts/.gitignore
  creo/scripts/getdeps.py
  creo/scripts/getdeps/__init__.py
  creo/scripts/getdeps/handler.py
  creo/scripts/getdeps/installer.py
  creo/scripts/getdeps/manifest.py
  creo/scripts/getdeps/platform.py
  creo/scripts/manifests/debootstrap
  creo/scripts/manifests/kconfig-frontends
  creo/scripts/manifests/make
Labels: Strategic, Python

#15 #9 : Implement side package managers detection module for `getdeps.py` script
  creo/Makefile
  creo/scripts/getdeps.py
  creo/scripts/getdeps/handler.py
  creo/scripts/getdeps/installer.py
  creo/scripts/getdeps/manifest.py
  creo/scripts/getdeps/platform.py
  creo/scripts/manifests/debootstrap
  creo/scripts/manifests/kconfig-frontends
  creo/scripts/manifests/make
Labels: Strategic, Python, Urgently
